[theme]
base = "light"
primaryColor = "#1FAA63"
backgroundColor = "#DCEAF7"
secondaryBackgroundColor = "#FFFFFF"
textColor = "#17324D"
font = "sans serif"

[server]
headless = true
runOnSave = true

[browser]
gatherUsageStats = false
